# Generated by Django 3.2.18 on 2023-05-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothings',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gaming',
            name='image',
        ),
        migrations.RemoveField(
            model_name='healthandbeauty',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homeandoffice',
            name='image',
        ),
        migrations.RemoveField(
            model_name='phoneandaccessories',
            name='image',
        ),
        migrations.AlterField(
            model_name='clothings',
            name='in_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clothings',
            name='price',
            field=models.FloatField(blank=True, default=2000.0, null=True),
        ),
        migrations.AlterField(
            model_name='gaming',
            name='in_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gaming',
            name='price',
            field=models.FloatField(blank=True, default=2000.0, null=True),
        ),
        migrations.AlterField(
            model_name='healthandbeauty',
            name='in_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthandbeauty',
            name='price',
            field=models.FloatField(blank=True, default=2000.0, null=True),
        ),
        migrations.AlterField(
            model_name='homeandoffice',
            name='in_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homeandoffice',
            name='price',
            field=models.FloatField(blank=True, default=2000.0, null=True),
        ),
        migrations.AlterField(
            model_name='phoneandaccessories',
            name='in_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phoneandaccessories',
            name='price',
            field=models.FloatField(blank=True, default=2000.0, null=True),
        ),
    ]
