# Generated by Django 3.2.18 on 2023-05-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_addproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproduct',
            old_name='customer',
            new_name='added_by',
        ),
    ]
