# Generated by Django 3.2.18 on 2023-05-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_customer_addproduct_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='category',
            field=models.CharField(blank=True, choices=[('Clothings', 'Clothings'), ('PhoneAndAccessories', 'Phone And Accessories'), ('HomeAndOffice', 'Home And Office'), ('HealthAndBeauty', 'Health An dBeauty'), ('Gaming', 'Gaming')], max_length=225, null=True, verbose_name='Categories'),
        ),
    ]
