# Generated by Django 3.2.18 on 2023-05-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_addproduct_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='discounted_price',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='discounted_price',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='clothings',
            name='discounted_price',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='gaming',
            name='discounted_price',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='healthandbeauty',
            name='discounted_price',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='homeandoffice',
            name='discounted_price',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='phoneandaccessories',
            name='discounted_price',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
