# Generated by Django 3.2.18 on 2023-05-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_addproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='category',
            field=models.CharField(blank=True, choices=[('Clothings', 'Clothings'), ('PhoneAndAccessories', 'Phone And Accessories'), ('HomeAndOffice', 'Home And Office'), ('HealthAndBeauty', 'Health And Beauty'), ('Gaming', 'Gaming')], max_length=225, null=True, verbose_name='Categories'),
        ),
    ]
