# Generated by Django 3.2.18 on 2023-05-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_cart_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='no_of_orders',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
