# Generated by Django 3.2.18 on 2023-05-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_cart_no_of_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='no_of_orders',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
