# Generated by Django 3.2.18 on 2023-05-21 21:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_alter_cart_no_of_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddProduct',
            new_name='AllProducts',
        ),
    ]
