# Generated by Django 3.2.18 on 2023-05-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_addproduct_allproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='in_stock',
        ),
    ]
