# Generated by Django 3.2.18 on 2023-05-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_cart_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_amount',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
